"""initial_schema

Revision ID: c4832cae2f8d
Revises:
Create Date: 2026-06-09 19:43:00.415596

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4832cae2f8d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "security_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_ip", sa.String(length=45), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "LOGIN_FAILURE",
                "PORT_SCAN",
                "BRUTE_FORCE",
                "SUSPICIOUS_REQUEST",
                "MALWARE_DETECTED",
                name="event_type_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="severity_level_enum"),
            nullable=False,
        ),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_security_events_occurred_at", "security_events", ["occurred_at"], unique=False
    )
    op.create_index("ix_security_events_source_ip", "security_events", ["source_ip"], unique=False)
    op.create_table(
        "threat_indicators",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("indicator_value", sa.String(length=512), nullable=False),
        sa.Column(
            "indicator_type",
            sa.Enum("IP", "DOMAIN", "HASH", name="indicator_type_enum"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("indicator_value"),
    )
    op.create_index(
        "ix_threat_indicators_value", "threat_indicators", ["indicator_value"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_threat_indicators_value", table_name="threat_indicators")
    op.drop_table("threat_indicators")
    op.drop_index("ix_security_events_source_ip", table_name="security_events")
    op.drop_index("ix_security_events_occurred_at", table_name="security_events")
    op.drop_table("security_events")
    # ### end Alembic commands ###
